image: registry.novisci.com/nsstat/statocker/r/pkgdev:3.6.3

stages:
  - testing
  - cran_check
  - package

testing:
  stage: testing
  script:
    - R -e 'install.packages("lenses")'
    - R -e 'install.packages("smd", repos = "http://cran.novisci.com")'
    - R -e 'devtools::check(manual = FALSE)'

cran_check:
# Per CRAN Repository Policy:
# I have checked the submission using R CMD check --as-cran and a current version
# of r-devel
  image: registry.novisci.com/nsstat/statocker/r/develcran
  stage: cran_check
  script:
    - R -e "install.packages(c('lenses'))"
    - R -e "install.packages(c('riskimator', 'smd'), repos = 'http://cran.novisci.com')"
    - R CMD check . --as-cran


package:
  stage: package
  script:
    - R -e 'install.packages("lenses")'
    - R -e "install.packages(c('riskimator', 'smd'), repos = 'http://cran.novisci.com')"
    - rm -rf .git
    - R CMD build .

site: 
  stage: package
  only:
     - master
  script:
     - R -e "install.packages(c('lenses'))"
     - R -e "install.packages(c('riskimator', 'smd'), repos = 'http://cran.novisci.com')"
     - R -e 'pkgdown::build_site()'
     - aws s3 sync $CI_PROJECT_DIR/docs/ s3://docs.novisci.com/stype/ --delete --acl public-read

minicran:
  stage: package
  only:
    - master
  script:
    - R -e "install.packages(c('lenses'))"
    - R -e "install.packages(c('riskimator', 'smd'), repos = 'http://cran.novisci.com')"
    - Rscript -e "library(miniCRAN); addLocalPackage('${CI_PROJECT_NAME}', pkgPath='..', path='/mnt/cran.novisci.com', type='source', build=TRUE)"
    - R -e "drat::archivePackages(repopath='/mnt/cran.novisci.com', pkg = '${CI_PROJECT_NAME}')"